# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4c3b7238b0ef288e849973e8b97fd1a63eeb9a4c623ed2cb46722f5f5d7f767fffb053959b9562d1bfd1bada78b9bd63d1b8c018aaa6238b1181192e6d1246b

test:
  secret_key_base: 8259e7271f39a676deb4cb7fc956858347c47da72aeeb2ce3963190ed2116f1602eb1b9f979847016fb7daa74e6ad34aef32fe549320f029e89caa45e9435144

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
